DROP TABLE IF EXISTS opt_orders;
DROP TABLE IF EXISTS opt_products;
DROP TABLE IF EXISTS opt_clients;

CREATE TABLE IF NOT EXISTS opt_clients (
    id UUID PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    surname VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(50) NOT NULL,
    address TEXT NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('active', 'inactive'))
);

CREATE TABLE IF NOT EXISTS opt_products (
    product_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR(255) NOT NULL,
    product_category VARCHAR(50) NOT NULL CHECK (
        product_category IN ('Category1', 'Category2', 'Category3', 'Category4', 'Category5')
    ),
    description TEXT
);

CREATE TABLE IF NOT EXISTS opt_orders (
    order_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_date DATE NOT NULL,
    client_id UUID,
    product_id INTEGER,
    CONSTRAINT fk_opt_orders_client
        FOREIGN KEY (client_id) REFERENCES opt_clients(id),
    CONSTRAINT fk_opt_orders_product
        FOREIGN KEY (product_id) REFERENCES opt_products(product_id)
);

select count(*) from opt_clients; --100,000
select count(*) from opt_orders; --1,000,000
select count(*) from opt_products; --10,000 

--NON-OPTIMIZED

explain analyze
select o.client_id,
c.name,
c.surname,
c.email,
o.order_date,
o.order_id,
p.product_id,
p.product_category
from public.opt_orders o
left join public.opt_clients c
on o.client_id = c.id 
left join public.opt_products p
on o.product_id = p.product_id
where o.order_date > '2026-06-01' ;

-- RESULTS
--Planning Time: 0.601 ms
--Execution Time: 119.042 ms


-- OPTIMIZED

create index if not exists idx_orders_date on public.opt_orders(order_date);
create index if not exists idx_client_id on public.opt_orders(client_id);
create index if not exists idx_product_id on public.opt_orders(product_id);

explain analyze
with filtered_order_date as (
select *
from public.opt_orders
where order_date > '2026-06-01'
)
select f.client_id,
c.name,
c.surname,
c.email,
f.order_date,
f.order_id,
p.product_id,
p.product_category
from filtered_order_date f
left join public.opt_clients c
on f.client_id = c.id 
left join public.opt_products p
on f.product_id = p.product_id

--RESULTS
--Planning Time: 0.508 ms
--Execution Time: 54.005 ms

-- OPTIMIZED WITH CONTROL

set enable_indexscan = off;

create index if not exists idx_orders_date on public.opt_orders(order_date);
create index if not exists idx_client_id on public.opt_orders(client_id);
create index if not exists idx_product_id on public.opt_orders(product_id);

explain analyze
with filtered_order_date as (
select *
from public.opt_orders
where order_date > '2026-06-01'
)
select f.client_id,
c.name,
c.surname,
c.email,
f.order_date,
f.order_id,
p.product_id,
p.product_category
from filtered_order_date f
left join public.opt_clients c
on f.client_id = c.id 
left join public.opt_products p
on f.product_id = p.product_id;

--RESULTS
--Planning Time: 0.366 ms
--Execution Time: 111.282 ms
